from curvature_flow import *
import numpy as np
import cmath
from scipy.interpolate import RegularGridInterpolator
import matplotlib.pyplot as plt
import config
"""
Uses the data generated by the curvature flow simulation in curvature_flow.py to calculate geodesics on the metric
given by the model in that file.
The heavy calculation lifting is done in the geodesic() function."""


def plot_geodesic(p, v, u_idx, steps, curve_plot=False, geo_plot=True):

    path, u, frame_time, r, theta = geodesic(p, v, u_idx, steps, plot=False)
    path = np.asarray(path, dtype=complex)

    if curve_plot == "single":
        plot_geodesic_on_frame(path, u, frame_time, r, theta, u_idx)

    if geo_plot:
        fig, ax = plt.subplots()

        ax.plot(path.real, path.imag, color="tab:blue", linewidth=2, label="geodesic")
        ax.scatter([path[0].real], [path[0].imag], color="tab:green", s=50, label="start")
        ax.scatter([path[-1].real], [path[-1].imag], color="tab:red", s=50, label="end")

        boundary_theta = np.linspace(-np.pi, np.pi, 400)
        ax.plot(np.cos(boundary_theta), np.sin(boundary_theta), "k--", linewidth=1, label="r = 1")

        ax.set_aspect("equal")
        ax.set_xlabel("Re(z)")
        ax.set_ylabel("Im(z)")
        ax.set_title(f"Geodesic on frame {u_idx}")
        ax.grid(True, alpha=0.3)
        ax.legend()
        plt.show()

def geodesic(u, r, theta, steps):
    """p is initial geodesic position, v is the initial velocity, both complex numbers.
    u_idx is the specific weight function at some time index"""

    p = config.P
    v = config.V

    # Select a weight function
    log_u = np.log(u)

    # Not sure if we will end up using this dt
    dt = 1e-2

    # Initial state
    gamma = p
    gamma_dot = v

    dr = r[1] - r[0]
    dtheta = theta[1] - theta[0]

    # Resulting path of the geodesic
    path = [gamma]

    # Cycling for neighbors
    log_u_left = np.roll(log_u, -1, axis=1)
    log_u_right = np.roll(log_u, 1, axis=1)

    # Calculate angular derivatives at all points
    dlogu_dtheta = (log_u_left - log_u_right) / (2 * dtheta)

    # Calculate radial derivatives
    dlogu_dr = np.zeros_like(log_u)
    dlogu_dr[1:-1] = (log_u[2:] - log_u[:-2]) / (2 * dr)

    # Precompute constants for O(1) index lookup
    r0, Nr = r[0], len(r)
    theta0, Ntheta = theta[0], len(theta)

    # Step through the simulation
    for i in range(steps):
        # Fast scalar coordinate extraction and nearest-index calculation
        r_gamma, theta_gamma = cmath.polar(gamma)
        
        ri = int(round((r_gamma - r0) / dr))
        if ri <= 0 or ri >= Nr - 1:
            break
        
        tj = int(round((theta_gamma - theta0) / dtheta)) % Ntheta

        r_val = r[ri]
        theta_val = theta[tj]

        # Get derivatives WRT theta and radius
        partial_theta = dlogu_dtheta[ri, tj]
        partial_r = dlogu_dr[ri, tj]

        dz = (cmath.exp(-1j * theta_val) / 2) * (partial_r - (1j * r_val * partial_theta))
        gamma_ddot = -dz * (gamma_dot ** 2)
        gamma_dot += dt * gamma_ddot
        gamma += dt * gamma_dot
        path.append(gamma)
        #print(abs(dz), abs(gamma_ddot))
    return path

def plot_geodesic_on_frame(path, u, frame_time, r, theta, u_idx):
    path_points = np.asarray(path, dtype=complex)
    if len(path_points) == 0:
        raise ValueError("path is empty")
    
    # Create a linear interpolation function for u
    # RegularGridInterpolator expects the axes (r, theta) and the values u
    interp_u = RegularGridInterpolator((r, theta), u, method='cubic', bounds_error=False, fill_value=None)


    R, TH = np.meshgrid(r, theta, indexing="ij")
    phi = (1 - BETA) * TH
    X = R * np.cos(phi)
    Y = R * np.sin(phi)

    z_path = []
    for gamma in path_points:
        # ri, tj = get_closest_point(gamma, r, theta)
        # z_path.append(u[ri, tj])
        z_path.append(interp_u([np.abs(gamma), np.angle(gamma)])[0])
    z_path = np.asarray(z_path, dtype=float)

    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")

    Z = u.copy()
    Z[0, 1:] = np.nan
    ax.plot_surface(X, Y, Z, cmap="jet", vmin=float(np.nanmin(u)), vmax=float(np.nanmax(u)), shade=True, alpha=0.85)
    ax.plot(path_points.real, path_points.imag, z_path, color="black", linewidth=2.5, label="geodesic")
    ax.scatter([path_points[0].real], [path_points[0].imag], [z_path[0]], color="tab:green", s=40, label="start")
    ax.scatter([path_points[-1].real], [path_points[-1].imag], [z_path[-1]], color="tab:red", s=40, label="end")

    ax.set_title(f"Geodesic on frame {u_idx} at t = {frame_time:.4f} s")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("u")
    ax.legend()
    plt.show()

def get_closest_point(p, r, theta) -> tuple: 
    """p is complex number, r is all radii, theta is all angles.
    returns a tuple like (radial_index, angular_index)"""

    r_gamma, theta_gamma = cmath.polar(p)
    
    dr = r[1] - r[0]
    dtheta = theta[1] - theta[0]
    
    i = int(round((r_gamma - r[0]) / dr))
    j = int(round((theta_gamma - theta[0]) / dtheta))
    
    i = max(0, min(len(r) - 1, i))
    j = j % len(theta)
    return i, j 


if __name__ == "__main__":

    plot_geodesic(config.P, config.V, config.U_IDX, config.STEPS, config.CURVE_PLOT, config.GEO_PLOT)
