from curvature_flow import *
import numpy as np
import matplotlib.pyplot as plt
"""
Uses the data generated by the curvature flow simulation in curvature_flow.py to calculate geodesics on the metric
given by the model in that file"""


def calculate_geodesic(p, v):
    """p is initial geodesic position, v is the initial velocity, both complex numbers"""
    frames, frame_times, r, theta = sim_in_polar(plot=False)

    # Infer the dt that we used in the simulation
    dt = frame_times[1] - frame_times[0]


def get_closest_point(p, frames:list, r, theta):
    """p is complex number, frames is a list representing the weight function at different
    times, radial indices, and theta indices."""

    







if __name__ == "__main__":
    calculate_geodesic(0, 0)