from curvature_flow import *
import numpy as np
import matplotlib.pyplot as plt
"""
Uses the data generated by the curvature flow simulation in curvature_flow.py to calculate geodesics on the metric
given by the model in that file"""


def plot_geodesic(p, v, u_idx, steps, plot=False):

    path = geodesic(p, v, u_idx, steps, plot=plot)

    path = np.asarray(path, dtype=complex)

    fig, ax = plt.subplots()

    ax.plot(path.real, path.imag, color="tab:blue", linewidth=2, label="geodesic")
    ax.scatter([path[0].real], [path[0].imag], color="tab:green", s=50, label="start")
    ax.scatter([path[-1].real], [path[-1].imag], color="tab:red", s=50, label="end")

    boundary_theta = np.linspace(-np.pi, np.pi, 400)
    ax.plot(np.cos(boundary_theta), np.sin(boundary_theta), "k--", linewidth=1, label="r = 1")

    ax.set_aspect("equal")
    ax.set_xlabel("Re(z)")
    ax.set_ylabel("Im(z)")
    ax.set_title(f"Geodesic on frame {u_idx}")
    ax.grid(True, alpha=0.3)
    ax.legend()
    plt.show()

def geodesic(p, v, u_idx, steps, plot=False) -> list:
    """p is initial geodesic position, v is the initial velocity, both complex numbers.
    u_idx is the specific weight function at some time index"""

    # Get weight function data
    frames, frame_times, r, theta = sim_in_polar(plot=plot)

    # Select a weight function
    u = frames[u_idx]
    log_u = np.log(u)

    # Not sure if we will end up using this dt
    dt = 1e-3

    # Initial state
    gamma = p
    gamma_dot = v

    dr = r[1] - r[0]
    dtheta = theta[1] - theta[0]

    # Resulting path of the geodesic
    path = [gamma]


    # Cycling for neighbors
    log_u_left = np.apply_along_axis(cycle_left, 1, log_u)
    log_u_right = np.apply_along_axis(cycle_right, 1, log_u)

    # Calculate angular derivatives at all points
    dlogu_dtheta = (log_u_left - log_u_right) / (2 * dtheta)

    # Calculate radial derivatives
    dlogu_dr = np.zeros_like(log_u)
    dlogu_dr[1:-1] = (log_u[2:] - log_u[:-2]) / (2 * dr)

    # Step through the simulation
    for i in range(steps):
        i, j = get_closest_point(gamma, r, theta)
        if i <= 0 or i >= len(r) - 1:
            break
        
        r_val = r[i]
        theta_val = theta[j]

        # Get derivatives WRT theta and radius
        partial_theta = dlogu_dtheta[i, j]
        partial_r = dlogu_dr[i, j]

        dz = (np.exp(-1j  * theta_val) / 2) * (partial_r - (1j * r_val*partial_theta))
        gamma__ddot = -dz * (gamma_dot ** 2)
        gamma_dot += dt * gamma__ddot
        gamma += dt * gamma_dot
        path.append(gamma)

    return path

def get_closest_point(p, r, theta) -> tuple: 
    """p is complex number, r is all radii, theta is all angles.
    returns a tuple like (radial_index, angular_index)"""

    r_gamma = abs(p)
    theta_gamma = np.angle(p)

    i = np.argmin(np.abs(r - r_gamma))
    j = np.argmin(np.abs((theta - theta_gamma + np.pi) % (2*np.pi) - np.pi))
    return i, j 


if __name__ == "__main__":

    plot_geodesic(0.25 + 0j, 0.2 + 0.1j, 10, 1000, True)
