from curvature_flow import *
import numpy as np
import matplotlib.pyplot as plt
"""
Uses the data generated by the curvature flow simulation in curvature_flow.py to calculate geodesics on the metric
given by the model in that file"""


def calculate_geodesic(p, v):
    """p is initial geodesic position, v is the initial velocity, both complex numbers"""
    frames, frame_times, r, theta = sim_in_polar(plot=False)

    # Infer the dt that we used in the simulation
    dt = frame_times[1] - frame_times[0]
    closest_point = get_closest_point(p, frames, r, theta)
    weight = 


def get_closest_point(p, r, theta) -> tuple:
    """p is complex number, r is all radii, theta is all angles.
    returns a tuple (radius index, angular index)"""

    r_gamma = abs(p)
    theta_gamma = np.angle(p)

    i = np.argmin(np.abs(r - r_gamma))
    j = np.argmin(np.abs((theta - theta_gamma + np.pi) % (2*np.pi) - np.pi))
    return i, j 


def sim_geodesic(p, v):
    # Initial geodesic
    gamma = p
    gamma_dot = v
    gamma_ddot = 0

    # Get weight function data
    frames, frame_times, r, theta = sim_in_polar(plot=False)

    # Infer the dt that we used in the simulation
    # Not sure if this will be the correct dt or not
    dt = frame_times[1] - frame_times[0]

    # Step through the simulation
    for t in range(len(frames)):
        closest_point = get_closest_point(p, r, theta)
        weight = frames[t][closest_point]

        dr = r[1] - r[0]
        dtheta = theta[1] - theta[0]

        # Geodesic equation
        log_u = np.log(weight)
        term_2 = (dr * log_u) - (dtheta * log_u) # Need to get r and i somehow
        term_1 = (np.e**)

    






if __name__ == "__main__":
    calculate_geodesic(0, 0)